### ISSUE TITLE
DaniaB24: prs-2019-p2p (void)

### ISSUE THREAD

**Issue by DaniaB24** [kottans/frontend-2022-homeworks#174]
https://github.com/kottans/frontend-2019-p2p/pull/198 - memory pair game
https://github.com/kottans/frontend-2019-p2p/pull/196 - oop tiny js world
https://github.com/kottans/frontend-2019-p2p/pull/181 - dom practice

**Comment by OleksiyRudenko** [comment]
Thank you for opening this.

As I can see, neither of the linked PRs is merged.
Some contain review feedback that is not addressed yet.
And [this one](https://github.com/kottans/frontend-2019-p2p/pull/181/files) contains multiple files not related to the task per se.

My proposal:
1. Improve your code as per reviewers' feedback.
1. Resubmit listed tasks in this repo.
1. Make sure each PR contains only relevant and required files/commits as per this repo submission instructions.

Let me know if you have any questions.

**Comment by OleksiyRudenko** [comment]
Closing as listed PRs are not approved and cannot be accounted for.

**Comment by OleksiyRudenko** [comment]
Re-opening to have visibility on progress across other homeworks repos.

**Comment by OleksiyRudenko** [comment]
Up
