### ISSUE TITLE
your-github-username: Import tasks from another homeworks repo

### ISSUE THREAD

**Issue by olehmaksymych** [kottans/frontend-2022-homeworks#401]
The following tasks were reviewed, approved and merged in other homework repos.

| [HTML & CSS Practice]          | PR link          https://github.com/kottans/frontend-2022-homeworks/pull/333                                                  |
|----------------------|--------------------------------------------------------------------|
| [Demo] |  https://olehmaksymych.github.io/html_popup/
| [Code base]  | https://github.com/olehmaksymych/html_popup 

I want them to be accounted.

Please check, confirm and assign relevant task labels.

**Comment by OleksiyRudenko** [comment]
@olehmaksymych you need to edit your issue so that it has tasks names and links to the PRs

**Comment by olehmaksymych** [comment]
> @olehmaksymych you need to edit your issue so that it has tasks names and links to the PRs Also edit title as appropriate

Could you please specify to what task I need to add an update?
Is that this pull request?:  https://github.com/kottans/frontend-2022-homeworks/pull/333 ?

**Comment by olehmaksymych** [comment]
> @olehmaksymych you need to edit your issue so that it has tasks names and links to the PRs Also edit title as appropriate

Could you please specify whether the title needs to be: "Hooli-style Popup" ?
Also, please clarify about ''tasks names and links to the PRs''  are you referring to the "HTML and CSS practice" task?

**Comment by olehmaksymych** [comment]
> @olehmaksymych you need to edit your issue so that it has tasks names and links to the PRs Also edit the title as appropriate

Please note that I have edited the links a few days ago: https://github.com/kottans/frontend-2022-homeworks/pull/333
Please check the picture:  https://imgur.com/bS0pLcU.png

**Comment by OleksiyRudenko** [comment]
@olehmaksymych you do not need to do this for tasks submitted to this homeworks repo. Your PR #333 is sufficient.
This is for students that started the course months ago in their own tempo, submitted code to different homewroks repos, and want their tasks to be accounted for.
Closing this issue.
